

# This file was *autogenerated* from the file abvar_setup.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1)
from lmf import db
from sage.all import PolynomialRing, ZZ
from collections import defaultdict
import re

slope_types = {('0A', '0B', '0C', '1A', '1B', '1C'): _sage_const_0 ,
               ('1/2A', '1/2B', '1/2C', '1/2D', '1/2E', '1/2F'): _sage_const_4 ,
               ('0A', '1/2A', '1/2B', '1/2C', '1/2D', '1A'): _sage_const_2 ,
               ('0A', '0B', '1/2A', '1/2B', '1A', '1B'): _sage_const_3 ,
               ('1/3A', '1/3B', '1/3C', '2/3A', '2/3B', '2/3C'): _sage_const_1 }

def get_data():
    R = PolynomialRing(ZZ, 'x')
    data = defaultdict(lambda: defaultdict(list))
    for rec in db.av_fq_isog.search({"g":_sage_const_3 }, ["label", "q", "hyp_count", "poly", "slopes"]):
        q = rec["q"]
        slopes = tuple(sorted(rec["slopes"]))
        have_hyp = (rec["hyp_count"] > _sage_const_0 )
        poly = R(rec["poly"])
        factors = poly.factor()
        fs = []
        for (fac, exp) in factors:
            if fac.degree() == _sage_const_1 :
                for i in range(exp//_sage_const_2 ):
                    fs.append(_sage_const_2 )
            else:
                for i in range(exp):
                    fs.append(fac.degree()) 
        fs.sort()
        exps = tuple(fs)
        data[q][exps, slope_types[slopes], have_hyp].append(rec["poly"])
    return data

def write_data(data):
    for q, D in data.items():
        for (exps, slopes, have_hyp), polys in D.items():
            
            filename = f"temp/data_{q}_{exps}_{slopes}_{have_hyp}.txt"
            with open(filename, "w") as F:
                for poly in polys:
                    _ = F.write(",".join(str(c) for c in poly) + "\n")


write_data(get_data())

