

# This file was *autogenerated* from the file char_2_hyp_point_count.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)
from collections import defaultdict
import sys
import os

n = int(sys.argv[_sage_const_1 ])
q = _sage_const_2 **n
block = int(sys.argv[_sage_const_2 ].split('_')[-_sage_const_1 ])
F = GF(q, names=('a',)); (a,) = F._first_ngens(1)
R = PolynomialRing(F, names=('x',)); (x,) = R._first_ngens(1)
final_hyp = defaultdict(list)
with open(os.path.join("data"+str(_sage_const_2 **n), "block_"+str(block)), 'r') as file:
    for line in file:
        polys = line.strip().split(';')
        final_hyp[R(sage_eval(polys[_sage_const_0 ], locals={'a':a}))].append(R(sage_eval(polys[_sage_const_1 ], locals={'a':a})))
all_hyp = []
for v in final_hyp:
    for u in final_hyp[v]:
        all_hyp.append((v, u))
out = defaultdict(int)

for i, (v, u) in enumerate(all_hyp):
    C = HyperellipticCurve(u, v)
    frob = C.frobenius_polynomial()
    out[frob] += _sage_const_1 

print(len(out))

out = [str(frob.list())+'\n' for frob in out.keys()]

with open(os.path.join("data"+str(_sage_const_2 **n), "out_"+str(block)), 'w') as outfile:
    outfile.writelines(out)

print("done with block " + str(block))

