

# This file was *autogenerated* from the file char_2_hyp_point_count.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_200 = Integer(200)
from collections import defaultdict
import sys
import os

q = _sage_const_8 
n = _sage_const_3 
block = int(sys.argv[_sage_const_1 ].split('_')[-_sage_const_1 ])
F = GF(q, names=('a',)); (a,) = F._first_ngens(1)
R = PolynomialRing(F, names=('x',)); (x,) = R._first_ngens(1)
final_hyp = defaultdict(list)
with open(os.path.join("data"+str(_sage_const_2 **n), "block_"+str(block)), 'r') as file:
    for line in file:
        polys = line.strip().split(';')
        # print(polys[1])
        # print(sage_eval(polys[1], locals={'a':a}))
        final_hyp[R(sage_eval(polys[_sage_const_0 ], locals={'a':a}))].append(R(sage_eval(polys[_sage_const_1 ], locals={'a':a})))
# print(final_hyp[1])
all_hyp = []
for q in final_hyp:
    for p in final_hyp[q]:
        all_hyp.append((q, p))
# all_hyp = [(q, p) for p in final_hyp[q] for q in final_hyp]
print(len(all_hyp))
out = defaultdict(int)

for i, (q, p) in enumerate(all_hyp):
    # print(q, p, type(p), type(q))
    if i % _sage_const_200  == _sage_const_0 :
        print(i)
    C = HyperellipticCurve(p, q)
    frob = C.frobenius_polynomial()
    out[frob] += _sage_const_1 

print(len(out))
# print(out)

out = [str(frob.list())+'\n' for frob in out.keys()]

with open(os.path.join("data_"+str(_sage_const_2 **n), "out_"+str(block)), 'w') as outfile:
    outfile.writelines(out)

print("done with block" + str(block))

