

# This file was *autogenerated* from the file combine_output_char_2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
import sys
import os
import ast

n = int(sys.argv[_sage_const_1 ])
q = _sage_const_2 **n
blocks = int(sys.argv[_sage_const_2 ])

out = dict()
R = PolynomialRing(ZZ, names=('x',)); (x,) = R._first_ngens(1)

for i in range(blocks):
    with open(os.path.join("data"+str(q), "out_"+str(i)), 'r') as weil_file:
            weil_polys = weil_file.readlines()
            for weil in weil_polys:
                weil_poly = R(ast.literal_eval(weil[:-_sage_const_1 ]))
                out[weil_poly] = True

with open(os.path.join("data"+str(q), "all_weil_polys_"+str(q)), 'w') as outfile:
    for weil in out:
        outfile.write(str(weil.list()) + '\n')

