

# This file was *autogenerated* from the file write_hyp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_4096 = Integer(4096); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
from sage.misc.cython import cython_import_all
import os

gen_hyp = cython_import_all("gen_hyp.spyx", globals())
import os
n = _sage_const_2 
final_hyp = generate_hyperelliptics_char2(n)
print(sum(len(x) for x in final_hyp.values()))
num_blocks = _sage_const_4096 
files = []
try:
    os.rmdir("data"+str(_sage_const_2 **n))
except:
    pass
os.mkdir("data"+str(_sage_const_2 **n))
for i in range(num_blocks):
    files.append(open(os.path.join("data"+str(_sage_const_2 **n), "block_"+str(i)), 'a+'))
i = _sage_const_0 
for q in final_hyp:
    print(q)
    for p in final_hyp[q]:
        files[i%num_blocks].write(str(q.list()) + ';' + str(p.list()) + '\n')
        i += _sage_const_1 

for file in files:
    file.close()

