

# This file was *autogenerated* from the file write_hyp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)
import os, shutil, sys
gen_hyp = load("gen_hyp_using_gap.sage") 

# set parameters
n = int(sys.argv[_sage_const_1 ])

# prepare output location
num_blocks = int(sys.argv[_sage_const_2 ])
files = []
try:
    shutil.rmtree("data"+str(_sage_const_2 **n))
except:
    pass
os.mkdir("data"+str(_sage_const_2 **n))

# create file handles
for i in range(num_blocks):
    files.append(open(os.path.join("data"+str(_sage_const_2 **n), "block_"+str(i)), 'a+'))

try:
    # write data
    i = _sage_const_0 
    for v, u in generate_hyperelliptics_char2(n):
        files[i%num_blocks].write(str(v.list()) + ';' + str(u.list()) + '\n')
        i += _sage_const_1 
    # close all files
    for file in files:
        file.close()

# if user interrupts, write output anyways
except KeyboardInterrupt:
    # close all files
    for file in files:
        file.close()



